### ISSUE TITLE
大牛啥时候可以添加IOS平台的呀

### ISSUE THREAD

**Issue by Feng2012** [TheBoneJarmer/cordova-plugin-phoneinfo#1]
大牛啥时候可以添加IOS平台的获取 手机的 IMEI和MEID信息的功能呀

**Comment by TheBoneJarmer** [comment]
Hello Feng

Would you please be so kind and translate this for me and for everyone else who does not speak Chinese? Thanks in advance!

With kind regards,
TheBoneJarmer

**Comment by TheBoneJarmer** [comment]
Going to close this issue due to inactivity
